use("test");

db.products.find();

// Aggregation -> process + transform + analyze data

// Aggregation is like a pipeline where data goes in raw and comes out as useful insights.

// aggregation--> stage 1 --> stage 2 --> stage 3 --> result

// db.products.find(
//   {
//     brand: 'Apple'
//   },
//   {
//     name:1,
//     price:1,
//     category:1,
//     brand:1,
//     _id:0
//   }
// ).sort({price:-1});  //normal way to do it

// Aggregation

// db.products.aggregate([
//   {
//     $match: {
//       brand: "Apple",
//     },
//   },
//   {
//     $project: {
//       name: 1,
//       price: 1,
//       category: 1,
//       brand: 1,
//       _id: 0,
//     },
//   },
//   {
//     $sort: {
//       price: -1,
//     },
//   },
// ]);

// db.products.aggregate([
//   {
//     $match: {
//       category: "Mobile",
//     },
//   },
//   {
//     $project: {
//       name: 1,
//       category: 1,
//       ratings: 1,
//       _id: 0,
//       averageRating: {
//         $avg: "$ratings",
//       },
//     },
//   },
// ]);

// steps in aggregation

// $match -> filter data

// $group -> group data

// $project -> shape data

// $sort -> sort data

// $lookup -> join data

// $unwind -> break arrays

// group

// db.products.aggregate([
//   {
//     $group: {
//       _id: "$category",
//       details: {
//         $push: {
//           productName: "$name",
//           price: "$price",
//         },
//       },
//     },
//   },
// ]);

// db.products.aggregate({
//   $group:{
//     _id:"$category",
//     total:{
//       $sum: "$price",

//     }
//   }
// })

// db.products.aggregate({  //this is for counting no of products in that category
//   $group: {
//     _id: "$category",
//     count: {
//       $sum: 1,
//     },
//   },
// });

// db.products.aggregate(
//   {
//     $project: {
//       name: 1,
//       price: 1,
//       _id: 0,
//       productsName: {
//         $toUpper: "$name",
//       },
//       inStock: "true",
//     },
//   },
//   {
//     $sort: {
//       price: -1,
//     },
//   },
// );

// lookup

// db.orders.aggregate(
//   {
//     $lookup:{
//       from: "products",
//       localField: "products.productId",
//       foreignField: "_id",
//       as: "productsDetails"
//     }
//   }
// )

// unwind

// db.products.aggregate([
//   {
//     $unwind:'$tags'
//   }
// ])

// Q 1.Imagine you need to find the total revenue generated by each product category in the last 24 hours.

db.orders.aggregate([
  {
    $project: {
      quantityDetails: "$products",
    },
  },
  {
    $unwind: "$quantityDetails",
  },
  {
    $lookup: {
      from: "products",
      localField: "quantityDetails.productId",
      foreignField: "_id",
      as: "productsDetails",
    },
  },
  {
    $unwind: "$productsDetails",
  },
  {
    $group: {
      _id: "$productsDetails.category",
      totalRevenue: {
        $sum: {
          $multiply: ["$quantityDetails.quantity", "$productsDetails.price"],
        },
      },

      // deatils:{
      //   $push : {
      //     quantityDetails: "$quantityDetails",
      //     productsDetails : "$productsDetails"
      //   }
      // }
    },
  },
]);
